version: 2.1

jobs:
  node-install:
    docker:
      - image: cimg/node:18.4.0
    steps:
      - checkout
      - run:
          name: "Install node dependencies"
          command: "time npm i"

workflows:
  deploy-node-app:
    jobs:
      - node-install
