version: 2.1

jobs:
  node-install:
    docker:
      - image: cimg/node:18.4.0
    steps:
      - checkout
      steps:
      - restore_cache:
          keys:
            # Find a cache corresponding to this specific package-lock.json checksum
            # when this file is changed, this key will fail
            - v1-npm-deps-{{ checksum "package-lock.json" }}
            # Find the most recently generated cache used from any branch
            - v1-npm-deps-
      - run:
          name: "Install node dependencies"
          command: "time npm i"
      - save_cache: # ** special step to save dependency cache **
          key: v1-npm-deps-{{ checksum "package-lock.json" }}
          paths:
            - "node_modules"

workflows:
  deploy-node-app:
    jobs:
      - node-install
